# Generated by Django 4.2.13 on 2024-05-09 15:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('customer_xid', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('owned_by', models.OneToOneField(db_column='owned_by', on_delete=django.db.models.deletion.CASCADE, to='app.account')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Failed'), (1, 'Success')])),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Deposit'), (-1, 'Withdrawal')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reference_id', models.UUIDField(default=uuid.uuid1, unique=True)),
                ('transacted_by', models.CharField(max_length=50)),
                ('wallet_id', models.ForeignKey(db_column='wallet_id', on_delete=django.db.models.deletion.CASCADE, to='app.wallet')),
            ],
        ),
    ]
